// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransportesGenesis.Data.Context;

#nullable disable

namespace TransportesGenesis.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.Alerta", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlerta"));

                    b.Property<int>("Activo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLectura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdDestinatario")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdRemitente")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdAlerta");

                    b.HasIndex("FechaEnvio");

                    b.HasIndex("IdDestinatario");

                    b.HasIndex("Leida");

                    b.ToTable("Alertas", "genesis");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.Alumnos", b =>
                {
                    b.Property<int>("IdAlumno")
                        .HasColumnType("int");

                    b.Property<int>("Activo")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdBusAsignado")
                        .HasColumnType("int");

                    b.Property<int>("IdPadre")
                        .HasColumnType("int");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(10, 7)");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(10, 7)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdAlumno");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("IdPadre");

                    b.ToTable("Alumnos", "genesis");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.AsignacionPilotoBus", b =>
                {
                    b.Property<int>("IdAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsignacion"));

                    b.Property<int>("Activo")
                        .HasColumnType("int");

                    b.Property<bool>("EsActual")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdBus")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuarioPiloto")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdAsignacion");

                    b.HasIndex("EsActual");

                    b.HasIndex("FechaAsignacion");

                    b.HasIndex("IdBus")
                        .IsUnique();

                    b.HasIndex("IdUsuarioPiloto");

                    b.ToTable("AsignacionPilotoBus", "genesis");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.AsistenciaAlumno", b =>
                {
                    b.Property<int>("IdAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsistencia"));

                    b.Property<int>("Activo")
                        .HasColumnType("int");

                    b.Property<bool>("AsisteMañana")
                        .HasColumnType("bit");

                    b.Property<bool>("AsisteTarde")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaConfirmacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAlumno")
                        .HasColumnType("int");

                    b.Property<int?>("IdBusTemporalMañana")
                        .HasColumnType("int");

                    b.Property<int?>("IdBusTemporalTarde")
                        .HasColumnType("int");

                    b.HasKey("IdAsistencia");

                    b.HasIndex("Fecha");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("IdAlumno");

                    b.ToTable("AsistenciaAlumno", "genesis");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.Banco", b =>
                {
                    b.Property<int>("IdBanco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBanco"));

                    b.Property<int>("Activo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdBanco");

                    b.HasIndex("FechaRegistro");

                    b.ToTable("Bancos", "genesis");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.Bus", b =>
                {
                    b.Property<int>("IdBus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBus"));

                    b.Property<int>("Activo")
                        .HasColumnType("int");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modelo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdBus");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Buses", "genesis");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.NotificacionProximidad", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<int>("Activo")
                        .HasColumnType("int");

                    b.Property<bool>("Enviada")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaHoraEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPadre")
                        .HasColumnType("int");

                    b.Property<int>("IdParada")
                        .HasColumnType("int");

                    b.Property<string>("TipoNotificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("Enviada");

                    b.HasIndex("FechaHoraEnvio");

                    b.HasIndex("IdPadre");

                    b.HasIndex("IdParada");

                    b.ToTable("NotificacionProximidad", "genesis");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.NotificacionRetraso", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<int>("Activo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNotificacionPadres")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRuta")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("NotificadoAPadres")
                        .HasColumnType("bit");

                    b.Property<int>("TiempoRetrasoMinutos")
                        .HasColumnType("int");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("FechaHora");

                    b.HasIndex("IdRuta");

                    b.HasIndex("NotificadoAPadres");

                    b.ToTable("NotificacionRetraso", "genesis");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.Padres", b =>
                {
                    b.Property<int>("IdPadre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPadre"));

                    b.Property<int>("Activo")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPadre");

                    b.HasIndex("FechaRegistro");

                    b.ToTable("Padres", "genesis");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<int>("Activo")
                        .HasColumnType("int");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaModif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAlumno")
                        .HasColumnType("int");

                    b.Property<int>("IdPadre")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoCuenta")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoRecorrido")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("MesPagado")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoParcial")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("PagoCompleto")
                        .HasColumnType("bit");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdPago");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdPadre");

                    b.HasIndex("IdTipoCuenta");

                    b.HasIndex("IdTipoRecorrido");

                    b.ToTable("Pagos", "genesis");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.Parada", b =>
                {
                    b.Property<int>("IdParada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParada"));

                    b.Property<int>("Activo")
                        .HasColumnType("int");

                    b.Property<bool>("Completada")
                        .HasColumnType("bit");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("HoraEstimada")
                        .HasColumnType("time");

                    b.Property<int>("IdAlumno")
                        .HasColumnType("int");

                    b.Property<int>("IdRuta")
                        .HasColumnType("int");

                    b.Property<decimal>("Latitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10, 7)");

                    b.Property<decimal>("Longitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10, 7)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("IdParada");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdRuta");

                    b.HasIndex("Orden");

                    b.ToTable("Paradas", "genesis");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.RegistroRecogida", b =>
                {
                    b.Property<int>("IdRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRegistro"));

                    b.Property<int>("Activo")
                        .HasColumnType("int");

                    b.Property<bool>("AlumnoPresente")
                        .HasColumnType("bit");

                    b.Property<string>("ConfirmadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaHoraRecogida")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAlumno")
                        .HasColumnType("int");

                    b.Property<int>("IdParada")
                        .HasColumnType("int");

                    b.Property<decimal?>("Latitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10, 7)");

                    b.Property<decimal?>("Longitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10, 7)");

                    b.HasKey("IdRegistro");

                    b.HasIndex("AlumnoPresente");

                    b.HasIndex("FechaHoraRecogida");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdParada");

                    b.ToTable("RegistroRecogida", "genesis");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.Ruta", b =>
                {
                    b.Property<int>("IdRuta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRuta"));

                    b.Property<int>("Activo")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("EsActiva")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdBus")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoRuta")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdRuta");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("IdBus");

                    b.HasIndex("TipoRuta");

                    b.ToTable("Rutas", "genesis");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.SolicitudTraslado", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<int>("Activo")
                        .HasColumnType("int");

                    b.Property<string>("AprobadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ComentarioAdmin")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaTraslado")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAlumno")
                        .HasColumnType("int");

                    b.Property<int?>("IdBusDestino")
                        .HasColumnType("int");

                    b.Property<int>("IdBusOrigen")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("FechaTraslado");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdBusOrigen");

                    b.ToTable("SolicitudTraslado", "genesis");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.TipoCuenta", b =>
                {
                    b.Property<int>("IdTipoCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoCuenta"));

                    b.Property<int>("Activo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdBanco")
                        .HasColumnType("int");

                    b.Property<int>("IdPadre")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTipoCuenta");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("IdBanco");

                    b.HasIndex("IdPadre");

                    b.ToTable("TipoCuenta", "genesis");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.TipoRecorridoPago", b =>
                {
                    b.Property<int>("IdTipoRecorrido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoRecorrido"));

                    b.Property<int>("Activo")
                        .HasColumnType("int");

                    b.Property<int>("DiaMaximoPago")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoRecorrido")
                        .HasColumnType("int");

                    b.HasKey("IdTipoRecorrido");

                    b.ToTable("TipoRecorridoPago", "genesis");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.UbicacionBusEnTiempoReal", b =>
                {
                    b.Property<int>("IdUbicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUbicacion"));

                    b.Property<decimal?>("Direccion")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdBus")
                        .HasColumnType("int");

                    b.Property<decimal>("Latitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10, 7)");

                    b.Property<decimal>("Longitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10, 7)");

                    b.Property<decimal?>("Velocidad")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("IdUbicacion");

                    b.HasIndex("FechaHora");

                    b.HasIndex("IdBus");

                    b.ToTable("UbicacionBusEnTiempoReal", "genesis");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Usuarios.AppUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.HasDiscriminator().HasValue("AppUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.Alumnos", b =>
                {
                    b.HasOne("TransportesGenesis.Models.DB.Negocio.TipoRecorridoPago", null)
                        .WithOne("IdAlumno")
                        .HasForeignKey("TransportesGenesis.Models.DB.Negocio.Alumnos", "IdAlumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportesGenesis.Models.DB.Negocio.Padres", "Padres")
                        .WithMany("AlumnosLink")
                        .HasForeignKey("IdPadre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Padres");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.AsignacionPilotoBus", b =>
                {
                    b.HasOne("TransportesGenesis.Models.DB.Negocio.Bus", "Bus")
                        .WithOne("AsignacionPilotoLink")
                        .HasForeignKey("TransportesGenesis.Models.DB.Negocio.AsignacionPilotoBus", "IdBus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.AsistenciaAlumno", b =>
                {
                    b.HasOne("TransportesGenesis.Models.DB.Negocio.Alumnos", "Alumno")
                        .WithMany("AsistenciasLink")
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.NotificacionProximidad", b =>
                {
                    b.HasOne("TransportesGenesis.Models.DB.Negocio.Padres", "Padre")
                        .WithMany()
                        .HasForeignKey("IdPadre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportesGenesis.Models.DB.Negocio.Parada", "Parada")
                        .WithMany("NotificacionesLink")
                        .HasForeignKey("IdParada")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Padre");

                    b.Navigation("Parada");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.NotificacionRetraso", b =>
                {
                    b.HasOne("TransportesGenesis.Models.DB.Negocio.Ruta", "Ruta")
                        .WithMany()
                        .HasForeignKey("IdRuta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruta");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.Pago", b =>
                {
                    b.HasOne("TransportesGenesis.Models.DB.Negocio.Alumnos", "Alumnos")
                        .WithMany("PagosLink")
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportesGenesis.Models.DB.Negocio.Padres", "Padres")
                        .WithMany("PagosLink")
                        .HasForeignKey("IdPadre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportesGenesis.Models.DB.Negocio.TipoCuenta", "TipoCuenta")
                        .WithMany("PagosLink")
                        .HasForeignKey("IdTipoCuenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportesGenesis.Models.DB.Negocio.TipoRecorridoPago", "TipoRecorridoPago")
                        .WithMany("PagosLink")
                        .HasForeignKey("IdTipoRecorrido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumnos");

                    b.Navigation("Padres");

                    b.Navigation("TipoCuenta");

                    b.Navigation("TipoRecorridoPago");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.Parada", b =>
                {
                    b.HasOne("TransportesGenesis.Models.DB.Negocio.Alumnos", "Alumno")
                        .WithMany("ParadasLink")
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportesGenesis.Models.DB.Negocio.Ruta", "Ruta")
                        .WithMany("ParadasLink")
                        .HasForeignKey("IdRuta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Ruta");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.RegistroRecogida", b =>
                {
                    b.HasOne("TransportesGenesis.Models.DB.Negocio.Alumnos", "Alumno")
                        .WithMany("RegistrosRecogidaLink")
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportesGenesis.Models.DB.Negocio.Parada", "Parada")
                        .WithMany("RegistrosRecogidaLink")
                        .HasForeignKey("IdParada")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Parada");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.Ruta", b =>
                {
                    b.HasOne("TransportesGenesis.Models.DB.Negocio.Bus", "Bus")
                        .WithMany("RutasLink")
                        .HasForeignKey("IdBus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.SolicitudTraslado", b =>
                {
                    b.HasOne("TransportesGenesis.Models.DB.Negocio.Alumnos", "Alumno")
                        .WithMany("SolicitudesTrasladoLink")
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportesGenesis.Models.DB.Negocio.Bus", "BusOrigen")
                        .WithMany()
                        .HasForeignKey("IdBusOrigen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("BusOrigen");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.TipoCuenta", b =>
                {
                    b.HasOne("TransportesGenesis.Models.DB.Negocio.Banco", "Bancos")
                        .WithMany("TipoCuentasLink")
                        .HasForeignKey("IdBanco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportesGenesis.Models.DB.Negocio.Padres", "Padres")
                        .WithMany("TipoCuentasLink")
                        .HasForeignKey("IdPadre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bancos");

                    b.Navigation("Padres");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.UbicacionBusEnTiempoReal", b =>
                {
                    b.HasOne("TransportesGenesis.Models.DB.Negocio.Bus", "Bus")
                        .WithMany("UbicacionesLink")
                        .HasForeignKey("IdBus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.Alumnos", b =>
                {
                    b.Navigation("AsistenciasLink");

                    b.Navigation("PagosLink");

                    b.Navigation("ParadasLink");

                    b.Navigation("RegistrosRecogidaLink");

                    b.Navigation("SolicitudesTrasladoLink");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.Banco", b =>
                {
                    b.Navigation("TipoCuentasLink");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.Bus", b =>
                {
                    b.Navigation("AsignacionPilotoLink");

                    b.Navigation("RutasLink");

                    b.Navigation("UbicacionesLink");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.Padres", b =>
                {
                    b.Navigation("AlumnosLink");

                    b.Navigation("PagosLink");

                    b.Navigation("TipoCuentasLink");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.Parada", b =>
                {
                    b.Navigation("NotificacionesLink");

                    b.Navigation("RegistrosRecogidaLink");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.Ruta", b =>
                {
                    b.Navigation("ParadasLink");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.TipoCuenta", b =>
                {
                    b.Navigation("PagosLink");
                });

            modelBuilder.Entity("TransportesGenesis.Models.DB.Negocio.TipoRecorridoPago", b =>
                {
                    b.Navigation("IdAlumno")
                        .IsRequired();

                    b.Navigation("PagosLink");
                });
#pragma warning restore 612, 618
        }
    }
}
